---
collections:
  - name: amazon.aws
    version: 7.2.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 3.0.0
  - name: ansible.controller
    version: 4.5.0
  - name: servicenow.itsm
    version: 2.4.0
  - name: servicenow.servicenow
    version: 1.0.6
  - name: community.mysql
    version: 3.8.0
  - name: community.general
    version: 8.1.0
  - name: community.aws
  - name: zjleblanc.reporting
    version: ">=1.3.0"
  - name: redhat.rhel_system_roles
    version: 1.23.0
