---
- name: Check for our mandatory variables
  # You can create a custom credential for the mandatory variables
  ansible.builtin.assert:
    that:
      - controller_url is defined
      - controller_user is defined
      - controller_passwd is defined
    fail_msg: "Please make sure your mandatory variables are set"
    success_msg: "All mandatory variables have been set"

# Gather the start time to use in a later playbook
- name: Record the aws_sync_time
  delegate_to: 127.0.0.1
  register: aws_sync_time_pre
  changed_when: false
  ansible.builtin.command:
    cmd: "date '+%H:%M:%S'"

# Make the start time available to other playbooks
- name: Capture the aws_sync_time
  ansible.builtin.set_stats:
    data:
      aws_sync_time: "{{ aws_sync_time_pre.stdout }}"

- name: Get Linux Daily Demo instances
  register: instance_info
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:Name: Linux Daily Demo
      instance-state-name: [running]

- name: Create a new token using username/password
  ansible.controller.token:
    controller_host: https://{{ controller_url }}
    controller_username: "{{ controller_user }}"
    controller_password: "{{ controller_passwd }}"
    validate_certs: false
    description: Daily Demo token
    scope: write
    state: present

- name: Update the AAP Managed Inventory with the Linux Daily Demo servers
  loop: "{{ instance_info['instances'] }}"
  ansible.controller.host:
    controller_host: https://{{ controller_url }}
    controller_oauthtoken: "{{ controller_token }}"
    validate_certs: false
    name: "{{ item['public_dns_name'] }}"
    inventory: "{{ managed_inventory_name }}"
    state: present
    enabled: true

- name: Create a group for our Linux Daily Demo servers
  loop: "{{ instance_info['instances'] }}"
  ansible.controller.group:
    controller_host: https://{{ controller_url }}
    controller_oauthtoken: "{{ controller_token }}"
    validate_certs: false
    name: rheldemo
    description: Automation Controller Group
    inventory: "{{ managed_inventory_name }}"
    hosts: "{{ item['public_dns_name'] }}"
    preserve_existing_hosts: true

- name: Update runtime inventory
  loop: "{{ instance_info['instances'] }}"
  ansible.builtin.add_host:
    name: "{{ item['public_dns_name'] }}"
    groups:
      - rheldemo

- name: Capture public ip address
  ansible.builtin.set_fact:
    my_public_ip: "{{ instance_info.instances[0].public_ip_address }}"
