---
- name: Create daily demo linux server
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:

    - name: Include the vm role
      tags:
        - create
      ansible.builtin.include_role:
        name: vm

    - name: Print all variables for localhost
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
