---
- name: Create daily demo linux server
  hosts: localhost
  connection: local

  tasks:

    - name: Include the vm role
      tags:
        - create
      ansible.builtin.include_role:
        name: vm

    - name: Include the update_sn_req_item role to update our ticket
      tags:
        - always
      vars:
        update_requested_item_comments: Your new virtual machine has been created
        update_requested_item_state: 2
      ansible.builtin.include_role:
        name: update_requested_item
