---
- name: Create daily demo linux server
  hosts: localhost
  connection: local

  tasks:

    - name: Include the vm role
      tags:
        - create
      ansible.builtin.include_role:
        name: vm
